### ISSUE TITLE
이미지 크기 조절방법

### ISSUE THREAD

**Issue by sooya233** [CSID-DGU/2021-1-OSSP1-Debugger-4#3]
face-landmark까지 진행하여, 해당 부분들의 좌표값을 얻었다.
이제, 마스크부분을 추출하기 위해서, 두 얼굴의 크기를 같게 만들어야된다.

현재 상태에서 생각하고 있는 부분은 두 가지이다.

- 두 사진에서 얼굴 부분만 따로 추출
- face-landmark에서 눈 부분의 좌표에 맞추어 이미지 크기 조절
  - 이때, 마스크를 낀 이미지의 크기는 그대로 놔두고, 정면에서의 얼굴만 크기를 조절한다.

**Comment by kny0ng125** [comment]
얼굴 부분만 따로 추출할 필요는 없어 보인다.
눈 부분의 face-landmark를 기준으로 두 이미지의 face-landmark를 일치시킨 후, 
얼굴의 크기 및 각도를 조절하여 합성하는 데 사용하면 문제 없을 것이다.

**Comment by sooya233** [comment]
그러면
- face-landmark에서 눈 부분의 좌표에 맞추기
  - 이때, 마스크를 낀 이미지의 크기는 그대로 놔두고, 정면에서의 얼굴만 크기를 조절한다.
- 왼쪽눈의 끝, 오른쪽 눈의 끝에 맞게 이미지 rotate시키기
- 각각 눈의 좌표에 맞게 이미지 크기 조절하기

**Comment by sooya233** [comment]
이미지의 크기를 변환시켰을 때, 위치가 달라짐에 따라 얼굴이 잡히지 않는 문제가 발생하였다.
![image](https://user-images.githubusercontent.com/71958885/117047572-01402480-ad4d-11eb-97ea-d1f182a88c61.png)

**Comment by sooya233** [comment]
해결완료
